#!/bin/bash

# Build script for Suitey
# Compiles all source modules into a single suitey.sh file

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR/src"
OUTPUT_FILE="$SCRIPT_DIR/suitey.sh"

# Colors for output
if [[ -t 1 ]]; then
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  NC='\033[0m'
else
  GREEN=''
  YELLOW=''
  NC=''
fi

echo -e "${GREEN}Building suitey.sh from source modules...${NC}"

# Start with shebang and set options
cat > "$OUTPUT_FILE" << 'HEADER'
#!/bin/bash

set -euo pipefail

# Project Scanner for Suitey
# Implements BATS project detection and test suite discovery
# This file is auto-generated by build.sh - do not edit manually

HEADER

# Add source files in dependency order
echo -e "${YELLOW}  Adding common.sh...${NC}"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Source: src/common.sh" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
cat "$SRC_DIR/common.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}  Adding adapter_registry.sh...${NC}"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Source: src/adapter_registry.sh" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
cat "$SRC_DIR/adapter_registry.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}  Adding framework_detector.sh...${NC}"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Source: src/framework_detector.sh" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
cat "$SRC_DIR/framework_detector.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}  Adding adapters/bats.sh...${NC}"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Source: src/adapters/bats.sh" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
cat "$SRC_DIR/adapters/bats.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}  Adding adapters/rust.sh...${NC}"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Source: src/adapters/rust.sh" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
cat "$SRC_DIR/adapters/rust.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}  Adding scanner.sh...${NC}"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Source: src/scanner.sh" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
cat "$SRC_DIR/scanner.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${YELLOW}  Adding main.sh...${NC}"
echo "# ============================================================================" >> "$OUTPUT_FILE"
echo "# Source: src/main.sh" >> "$OUTPUT_FILE"
echo "# ============================================================================" >> "$OUTPUT_FILE"
cat "$SRC_DIR/main.sh" >> "$OUTPUT_FILE"

# Make the output file executable
chmod +x "$OUTPUT_FILE"

echo -e "${GREEN}✓ Build complete: $OUTPUT_FILE${NC}"

